### ISSUE TITLE
Update to Mindustry v7

### ISSUE THREAD

**Issue by Nester23** [Antyos/vscode-mlog#3]
**There are new sensors, blocks, units and even a few new instructions in the game that aren't supported.**

**Comment by Antyos** [comment]
Do you know of where I can find a complete list of the new blocks, units, commands, etc.? I can't seem to find a comprehensive changelog of v7.

Early on, I made the design decision of only supporting syntax highlighting for built-in blocks/units which I have since regretted. I plan on changing this so that all `@names` will be highlighted, enabling support for future versions as well as mods.

**Comment by Nester23** [comment]
> Do you know of where I can find a complete list of the new blocks, units, commands, etc.? I can't seem to find a comprehensive changelog of v7.

I know that there's an official changelog in ![the official Mindustry GitHub page](https://github.com/Anuken/Mindustry/releases), but I'm not sure if there is a full list of changes for logic sensors/types and all that anywhere.
_I can try to make it myself, so download an older version of Mindustry and compare it with the current one, but I'm not sure about blocks, since there would be more of them in the future._

**Comment by Nester23** [comment]
> _I can try to make it myself, so download an older version of Mindustry and compare it with the current one._

**So here's the list of features I found missing:**
---
### **Sensor changes**
- **Added new sensors:**
```
@progress
@timescale
@size
@dead
@range
@boosting
@controller
```
![изображение](https://user-images.githubusercontent.com/66305483/129883263-7f2115e8-c595-46c6-b526-39eec6bae326.png)
- **`@commanded` is deprecated:**
![изображение](https://user-images.githubusercontent.com/66305483/129890138-3f3f3120-75c1-4dc9-b72e-7ebe50878538.png)
---
### **Operation changes**
- **Replaced _atan2_ with _angle_ and _dst_ with _len_:**
![изображение](https://user-images.githubusercontent.com/66305483/129883329-02382a72-04e9-4c35-a14c-facf521a0b9f.png)
- **Added operations _asin_, _acos_, _atan_:**
![изображение](https://user-images.githubusercontent.com/66305483/129883567-d62f5510-5764-41e9-beb0-945843427a49.png)
- **Added _strictEqual_ to both operations and jumps:**
![изображение](https://user-images.githubusercontent.com/66305483/129891179-b484115e-7407-410f-a07f-3935a0bce41d.png)

**New instructions**
---
### **Wait:**
![изображение](https://user-images.githubusercontent.com/66305483/129884458-5b800681-d40a-4ef9-be4e-3131fc71db6e.png)
### **Lookup:**
![изображение](https://user-images.githubusercontent.com/66305483/129884660-67a68f3a-a983-4eb5-a0e1-0b8aab727119.png)
![изображение](https://user-images.githubusercontent.com/66305483/129885186-25d10de8-631a-4ae4-a648-c5fe08ffec0c.png)

**New constants**
---
- **`@tick`**
- **Lookup constants:**
```
@unitCount
@itemCount
@liquidCount
@blockCount
```
- **Controlled sensor constants:**
```
@ctrlProcessor
@ctrlPlayer
@ctrlFormation
```
![изображение](https://user-images.githubusercontent.com/66305483/129887110-35e9dc6d-ff8e-4c8a-af1e-ce6220ced227.png)

**Jump labels**
---
- **Now jumps can point to labels:**
```
sensor copper container1 @copper

jump isEnabled_true equal isEnabled true
op greaterThanEq isEnabled copper 100 #Copper >= 100
jump exit_elseIf always 0 0

isEnabled_true:
op greaterThanEq isEnabled copper 50 #Copper >= 50

exit_elseIf:
control enabled unloader1 isEnabled 0 0 0
```
![изображение](https://user-images.githubusercontent.com/66305483/129915978-0560aefd-1242-4362-a3f7-122e0dad67a9.png)
---
So, this is about all I can remember and find right now, maybe there's some constant missing? idk, but I hope this helps.
[new stuff.txt](https://github.com/Antyos/vscode-mlog/files/7006872/new.stuff.txt)

**Comment by Antyos** [comment]
This is a great help, thank you!

**Comment by Antyos** [comment]
I have made a number of changes to the grammar for Mindustry v7, as you outline above:

## Changes

### Added
- Operators: `strictEqual`, `asin`, `acos`, and `atan`
- Commands: `wait` and `lookup`
- At-names: `@tick`, `@blockCount`, `@unitCount`, `@itemCount`, `@liquidCount`, `@ctrlProcessor`, `@ctrlPlayer`, `@ctrlFormation`
- Other at-names will still be highlighted
- Jump labels syntax

### Replaced
- `atan2` and `dst` with `angle` and `len`, respectively

### Deprecated
- At-names: `@commanded`
- Operators: `atan2`, `dst` (not technically deprecated in-game)

### Screenshot

![image](https://user-images.githubusercontent.com/17516195/130270625-faf1db74-d6e9-4129-b6f6-9e7502fc8557.png)


## Going forward

I have a few questions/concerns about releasing the update--

Mindustry v7 is still in Beta as of now. If I publish these changes to the extension now, I am unsure how it will affect users still playing v6. This is especially true for the deprecated variable `@commanded`.

Officially, it seems like `atan2` and `dst` are still supported in the [source code](https://github.com/Anuken/Mindustry/blob/02e68d27a3e4a045a174223e158a7b76dd5cc454/core/src/mindustry/logic/LParser.java#L11-L14), however I am unsure if they will remain that way. As it seems like Anuken wants people to use `angle` and `len`, I decided to classify the other two as deprecated.

One possibility is making a language pack for each version of the game, but I'm not sure that I like that idea.

Do you know which (if any) of these changes have been implemented in the current stable release of Mindustry? (I haven't been playing it lately)

**Comment by Nester23** [comment]
> Which (if any) of these changes have been implemented in the current stable release of Mindustry? 

Most of them are implemented to the stable version of Mindustry including deprecation of `@commanded` and replacement of _atan2_ and _dst_.

The additions Mindustry v7 brings are `wait` and `lookup` plus _asin_, _acos_, and _atan_, operations, but supporting them shouldn't interfere with anything,

**Comment by Antyos** [comment]
Perfect! I'll try and get a new release out later today!

**Comment by VladisSVostok2000** [comment]
omg this is most useful post. I used my own c# programm to make labels-like jumps...
